apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-service
  namespace: banking-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: audit-service
  template:
    metadata:
      labels:
        app: audit-service
    spec:
      containers:
      - name: audit-service
        image: <ECR_ACCOUNT_ID>.dkr.ecr.<AWS_REGION>.amazonaws.com/banking/audit-service:latest
        ports:
        - containerPort: 8084
        env:
        - name: DB_USERNAME
          value: "root"
        - name: DB_PASSWORD
          value: "password123"
        - name: DB_HOST
          value: "<RDS_ENDPOINT>"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: audit-service
  namespace: banking-system
spec:
  selector:
    app: audit-service
  ports:
  - port: 8084
    targetPort: 8084
  type: ClusterIP
