apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
  namespace: banking-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transaction-service
  template:
    metadata:
      labels:
        app: transaction-service
    spec:
      containers:
      - name: transaction-service
        image: <ECR_ACCOUNT_ID>.dkr.ecr.<AWS_REGION>.amazonaws.com/banking/transaction-service:latest
        ports:
        - containerPort: 8082
        env:
        - name: DB_USERNAME
          value: "root"
        - name: DB_PASSWORD
          value: "password123"
        - name: DB_HOST
          value: "<RDS_ENDPOINT>"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  namespace: banking-system
spec:
  selector:
    app: transaction-service
  ports:
  - port: 8082
    targetPort: 8082
  type: ClusterIP
