apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: banking-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: <ECR_ACCOUNT_ID>.dkr.ecr.<AWS_REGION>.amazonaws.com/banking/webapp:latest
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_URL
          value: "http://<API_GATEWAY_LB_URL>"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: banking-system
spec:
  selector:
    app: webapp
  ports:
  - port: 3000
    targetPort: 3000
  type: LoadBalancer